Resources:
  DynamoDBBackupExportItemsToS3LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dynamoDB-backup-export-items-lambdaRole
      Description: Role to allow export of items from DynamoDB tables to S3
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StsBackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - arn:aws:iam::${self:custom.SSM_ORIGIN_ACCOUNT_ID}:role/${self:custom.SSM_ROLE_TO_ASSUME}
        - PolicyName: DynamoDBBackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource:
                  - arn:aws:dynamodb:${self:provider.region}:${self:custom.SSM_ORIGIN_ACCOUNT_ID}:table/*
        - PolicyName: S3BackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::${self:custom.S3_BUCKET_NAME}
                  - arn:aws:s3:::${self:custom.S3_BUCKET_NAME}/*
        - PolicyName: SqsBackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource:
                  - ${self:custom.SSM_EXPORT_ITEMS_TO_S3_QUEUE_ARN}
        - PolicyName: CloudwatchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:TagResource
                Resource:
                  - arn:aws:logs:${self:provider.region}:${self:custom.SSM_BACKUP_ACCOUNT_ID}:log-group:*

