STAGE: ${sls:stage}
REGION: ${self:provider.region}
SERVICE_NAME_PREFIX: ${self:service}-${sls:stage}

BUCKET_NAME: ${self:custom.S3_BUCKET_NAME}

EXPORT_ITEMS_TO_S3_FIFO_QUEUE: ${self:custom.SQS_EXPORT_ITEMS_TO_S3_FIFO_QUEUE}
PROVISION_TABLES_QUEUE: ${self:custom.SQS_PROVISION_TABLES_QUEUE}
WRITE_ITEMS_QUEUE: ${self:custom.SQS_WRITE_ITEMS_QUEUE}

ROLE_TO_ASSUME: ${self:custom.SSM_ROLE_TO_ASSUME}
ORIGIN_ACCOUNT_ID: ${self:custom.SSM_ORIGIN_ACCOUNT_ID}
BACKUP_ACCOUNT_ID: ${self:custom.SSM_BACKUP_ACCOUNT_ID}
SLACK_WEBHOOK_URL: ${self:custom.SSM_SLACK_WEBHOOK_URL}
